export const mockBookings = [
    { 
    id: '1', 
    client: 'John Doe', 
    phone: '555-1234', 
    service: 'Haircut', 
    price: 30, 
    date: '2025-08-26', 
    startTime: '10:00 AM', 
    endTime: '11:00 AM', 
    status: 'Confirmed' 
  },
  { 
    id: '2', 
    client: 'Jane Smith', 
    phone: '555-5678', 
    service: 'Manicure', 
    price: 20, 
    date: '2025-08-27', 
    startTime: '2:00 PM', 
    endTime: '3:00 PM', 
    status: 'Pending' 
  },
  { 
    id: '3', 
    client: 'Alice Brown', 
    phone: '555-9012', 
    service: 'Facial', 
    price: 50, 
    date: '2025-08-28', 
    startTime: '1:00 PM', 
    endTime: '2:00 PM', 
    status: 'Confirmed' 
  },
];
export const mockClients = [
  { 
    id: '1', 
    name: 'John Doe', 
    phone: '555-1234', 
    email: 'john.doe@example.com', 
    actions: '' 
  },
  { 
    id: '2', 
    name: 'Jane Smith', 
    phone: '555-5678', 
    email: 'jane.smith@example.com', 
    actions: '' 
  },
  { 
    id: '3', 
    name: 'Alice Brown', 
    phone: '555-9012', 
    email: 'alice.brown@example.com', 
    actions: '' 
  },
];
export const mockTimeSlots = [
  { id: '1', day: 'Monday', startTime: '9:00 AM', endTime: '10:00 AM', action: 'Edit' },
  { id: '2', day: 'Monday', startTime: '10:00 AM', endTime: '11:00 AM', action: 'Edit' },
  { id: '3', day: 'Monday', startTime: '11:00 AM', endTime: '12:00 PM', action: 'Edit' },
  { id: '4', day: 'Tuesday', startTime: '9:00 AM', endTime: '10:00 AM', action: 'Edit' },
  { id: '5', day: 'Tuesday', startTime: '1:00 PM', endTime: '2:00 PM', action: 'Edit' },
  { id: '6', day: 'Tuesday', startTime: '3:00 PM', endTime: '4:00 PM', action: 'Edit' },
  { id: '7', day: 'Wednesday', startTime: '10:00 AM', endTime: '11:00 AM', action: 'Edit' },
  { id: '8', day: 'Wednesday', startTime: '12:00 PM', endTime: '1:00 PM', action: 'Edit' },
  { id: '9', day: 'Wednesday', startTime: '2:00 PM', endTime: '3:00 PM', action: 'Edit' },
  { id: '10', day: 'Thursday', startTime: '9:00 AM', endTime: '10:00 AM', action: 'Edit' },
  { id: '11', day: 'Thursday', startTime: '11:00 AM', endTime: '12:00 PM', action: 'Edit' },
  { id: '12', day: 'Thursday', startTime: '4:00 PM', endTime: '5:00 PM', action: 'Edit' },
  { id: '13', day: 'Friday', startTime: '10:00 AM', endTime: '11:00 AM', action: 'Edit' },
  { id: '14', day: 'Friday', startTime: '1:00 PM', endTime: '2:00 PM', action: 'Edit' },
  { id: '15', day: 'Friday', startTime: '3:00 PM', endTime: '4:00 PM', action: 'Edit' },
  { id: '16', day: 'Saturday', startTime: '9:00 AM', endTime: '10:00 AM', action: 'Edit' },
  { id: '17', day: 'Saturday', startTime: '11:00 AM', endTime: '12:00 PM', action: 'Edit' },
  { id: '18', day: 'Saturday', startTime: '2:00 PM', endTime: '3:00 PM', action: 'Edit' },
  { id: '19', day: 'Saturday', startTime: '4:00 PM', endTime: '5:00 PM', action: 'Edit' },
  { id: '20', day: 'Sunday', startTime: '10:00 AM', endTime: '11:00 AM', action: 'Edit' },
  { id: '21', day: 'Sunday', startTime: '12:00 PM', endTime: '1:00 PM', action: 'Edit' },
  { id: '22', day: 'Sunday', startTime: '2:00 PM', endTime: '3:00 PM', action: 'Edit' },
  { id: '23', day: 'Sunday', startTime: '3:00 PM', endTime: '4:00 PM', action: 'Edit' },
  { id: '24', day: 'Monday', startTime: '12:00 PM', endTime: '1:00 PM', action: 'Edit' },
  { id: '25', day: 'Tuesday', startTime: '2:00 PM', endTime: '3:00 PM', action: 'Edit' },
];
export const mockServices = [
  { id: '1', service: 'Haircut', subCategory: 'Men', price: 30, time: '30 mins', actions: '' },
  { id: '2', service: 'Haircut', subCategory: 'Women', price: 40, time: '45 mins', actions: '' },
  { id: '3', service: 'Manicure', subCategory: 'Nails', price: 20, time: '45 mins', actions: '' },
  { id: '4', service: 'Pedicure', subCategory: 'Nails', price: 25, time: '50 mins', actions: '' },
  { id: '5', service: 'Facial', subCategory: 'Skin Care', price: 50, time: '60 mins', actions: '' },
  { id: '6', service: 'Deep Cleansing Facial', subCategory: 'Skin Care', price: 70, time: '75 mins', actions: '' },
  { id: '7', service: 'Massage', subCategory: 'Relaxation', price: 80, time: '90 mins', actions: '' },
  { id: '8', service: 'Hot Stone Massage', subCategory: 'Relaxation', price: 100, time: '100 mins', actions: '' },
  { id: '9', service: 'Hair Coloring', subCategory: 'Hair', price: 60, time: '120 mins', actions: '' },
  { id: '10', service: 'Hair Styling', subCategory: 'Hair', price: 35, time: '40 mins', actions: '' },
  { id: '11', service: 'Beard Trim', subCategory: 'Men Grooming', price: 15, time: '20 mins', actions: '' },
  { id: '12', service: 'Shaving', subCategory: 'Men Grooming', price: 10, time: '15 mins', actions: '' },
  { id: '13', service: 'Waxing', subCategory: 'Body Care', price: 45, time: '50 mins', actions: '' },
  { id: '14', service: 'Threading', subCategory: 'Face Care', price: 12, time: '15 mins', actions: '' },
  { id: '15', service: 'Makeup', subCategory: 'Beauty', price: 120, time: '150 mins', actions: '' },
  { id: '16', service: 'Bridal Makeup', subCategory: 'Beauty', price: 200, time: '180 mins', actions: '' },
  { id: '17', service: 'Body Scrub', subCategory: 'Skin Care', price: 55, time: '70 mins', actions: '' },
  { id: '18', service: 'Hair Spa', subCategory: 'Hair', price: 65, time: '75 mins', actions: '' },
  { id: '19', service: 'Keratin Treatment', subCategory: 'Hair', price: 150, time: '180 mins', actions: '' },
  { id: '20', service: 'Aromatherapy', subCategory: 'Relaxation', price: 90, time: '100 mins', actions: '' },
];


export const mockUsers = [
  { id: '1', name: 'Emma Wilson', email: 'emma.wilson@example.com', role: 'Staff', leaveStatus: 'None', available: true, action: 'Edit' },
  { id: '2', name: 'Liam Johnson', email: 'liam.johnson@example.com', role: 'Manager', leaveStatus: 'Pending', available: false, action: 'View' },
  { id: '3', name: 'Olivia Smith', email: 'olivia.smith@example.com', role: 'Staff', leaveStatus: 'Approved', available: false, action: 'Edit' },
  { id: '4', name: 'Noah Brown', email: 'noah.brown@example.com', role: 'Supervisor', leaveStatus: 'None', available: true, action: 'View' },
  { id: '5', name: 'Ava Davis', email: 'ava.davis@example.com', role: 'Staff', leaveStatus: 'None', available: true, action: 'Edit' },
  { id: '6', name: 'William Lee', email: 'william.lee@example.com', role: 'Manager', leaveStatus: 'Rejected', available: true, action: 'View' },
  { id: '7', name: 'Sophia Martinez', email: 'sophia.martinez@example.com', role: 'Staff', leaveStatus: 'None', available: true, action: 'Edit' },
  { id: '8', name: 'James Taylor', email: 'james.taylor@example.com', role: 'Staff', leaveStatus: 'Pending', available: false, action: 'View' },
  { id: '9', name: 'Isabella Garcia', email: 'isabella.garcia@example.com', role: 'Supervisor', leaveStatus: 'None', available: true, action: 'Edit' },
  { id: '10', name: 'Alexander Clark', email: 'alexander.clark@example.com', role: 'Staff', leaveStatus: 'Approved', available: false, action: 'View' },
  { id: '11', name: 'Mia Rodriguez', email: 'mia.rodriguez@example.com', role: 'Staff', leaveStatus: 'None', available: true, action: 'Edit' },
  { id: '12', name: 'Ethan Walker', email: 'ethan.walker@example.com', role: 'Manager', leaveStatus: 'None', available: true, action: 'View' },
  { id: '13', name: 'Charlotte Hall', email: 'charlotte.hall@example.com', role: 'Staff', leaveStatus: 'Pending', available: false, action: 'Edit' },
  { id: '14', name: 'Daniel Allen', email: 'daniel.allen@example.com', role: 'Supervisor', leaveStatus: 'None', available: true, action: 'View' },
  { id: '15', name: 'Amelia Young', email: 'amelia.young@example.com', role: 'Staff', leaveStatus: 'Approved', available: false, action: 'Edit' },
  { id: '16', name: 'Henry King', email: 'henry.king@example.com', role: 'Staff', leaveStatus: 'None', available: true, action: 'View' },
  { id: '17', name: 'Harper Wright', email: 'harper.wright@example.com', role: 'Manager', leaveStatus: 'Rejected', available: true, action: 'Edit' },
  { id: '18', name: 'Lucas Scott', email: 'lucas.scott@example.com', role: 'Staff', leaveStatus: 'None', available: true, action: 'View' },
  { id: '19', name: 'Evelyn Adams', email: 'evelyn.adams@example.com', role: 'Supervisor', leaveStatus: 'Pending', available: false, action: 'Edit' },
  { id: '20', name: 'Jack Baker', email: 'jack.baker@example.com', role: 'Staff', leaveStatus: 'None', available: true, action: 'View' },
  { id: '21', name: 'Aria Nelson', email: 'aria.nelson@example.com', role: 'Staff', leaveStatus: 'Approved', available: false, action: 'Edit' },
  { id: '22', name: 'Mason Carter', email: 'mason.carter@example.com', role: 'Manager', leaveStatus: 'None', available: true, action: 'View' },
  { id: '23', name: 'Lily Mitchell', email: 'lily.mitchell@example.com', role: 'Staff', leaveStatus: 'None', available: true, action: 'Edit' },
  { id: '24', name: 'Logan Perez', email: 'logan.perez@example.com', role: 'Supervisor', leaveStatus: 'Pending', available: false, action: 'View' },
  { id: '25', name: 'Grace Roberts', email: 'grace.roberts@example.com', role: 'Staff', leaveStatus: 'None', available: true, action: 'Edit' }
];

export const mockOffers = [
  { id: '1', title: 'Summer Sale', type: 'Percentage', value: '20%', validFrom: '2025-06-01', validTo: '2025-08-31', status: 'Active', action: 'Edit' },
  { id: '2', title: 'Winter Discount', type: 'Fixed', value: '$50', validFrom: '2025-12-01', validTo: '2025-12-31', status: 'Pending', action: 'View' },
  { id: '3', title: 'New User Promo', type: 'Percentage', value: '15%', validFrom: '2025-01-01', validTo: '2025-12-31', status: 'Active', action: 'Edit' },
  { id: '4', title: 'Loyalty Reward', type: 'Fixed', value: '$10', validFrom: '2025-03-01', validTo: '2025-06-30', status: 'Expired', action: 'View' },
  { id: '5', title: 'Flash Sale', type: 'Percentage', value: '30%', validFrom: '2025-07-15', validTo: '2025-07-20', status: 'Expired', action: 'Edit' },
  { id: '6', title: 'Holiday Special', type: 'Fixed', value: '$25', validFrom: '2025-11-01', validTo: '2025-12-25', status: 'Pending', action: 'View' },
  { id: '7', title: 'Back to School', type: 'Percentage', value: '10%', validFrom: '2025-08-01', validTo: '2025-09-30', status: 'Active', action: 'Edit' },
  { id: '8', title: 'VIP Discount', type: 'Fixed', value: '$100', validFrom: '2025-02-01', validTo: '2025-12-31', status: 'Active', action: 'View' },
  { id: '9', title: 'Weekend Deal', type: 'Percentage', value: '25%', validFrom: '2025-09-05', validTo: '2025-09-07', status: 'Expired', action: 'Edit' },
  { id: '10', title: 'Early Bird', type: 'Fixed', value: '$15', validFrom: '2025-04-01', validTo: '2025-04-15', status: 'Expired', action: 'View' },
  { id: '11', title: 'Family Pack', type: 'Percentage', value: '20%', validFrom: '2025-07-01', validTo: '2025-08-15', status: 'Active', action: 'Edit' },
  { id: '12', title: 'Refer a Friend', type: 'Fixed', value: '$5', validFrom: '2025-01-01', validTo: '2025-12-31', status: 'Active', action: 'View' },
  { id: '13', title: 'Seasonal Offer', type: 'Percentage', value: '15%', validFrom: '2025-10-01', validTo: '2025-11-30', status: 'Pending', action: 'Edit' },
  { id: '14', title: 'Clearance Sale', type: 'Fixed', value: '$30', validFrom: '2025-09-01', validTo: '2025-09-30', status: 'Expired', action: 'View' },
  { id: '15', title: 'Student Discount', type: 'Percentage', value: '10%', validFrom: '2025-08-15', validTo: '2025-12-31', status: 'Active', action: 'Edit' },
  { id: '16', title: 'Bulk Purchase', type: 'Fixed', value: '$20', validFrom: '2025-05-01', validTo: '2025-07-31', status: 'Expired', action: 'View' },
  { id: '17', title: 'Festive Deal', type: 'Percentage', value: '25%', validFrom: '2025-12-10', validTo: '2025-12-31', status: 'Pending', action: 'Edit' },
  { id: '18', title: 'Midweek Offer', type: 'Fixed', value: '$10', validFrom: '2025-06-10', validTo: '2025-06-15', status: 'Expired', action: 'View' },
  { id: '19', title: 'Premium Plan', type: 'Percentage', value: '30%', validFrom: '2025-03-01', validTo: '2025-12-31', status: 'Active', action: 'Edit' },
  { id: '20', title: 'Last Minute', type: 'Fixed', value: '$40', validFrom: '2025-08-20', validTo: '2025-08-25', status: 'Expired', action: 'View' },
  { id: '21', title: 'Group Discount', type: 'Percentage', value: '20%', validFrom: '2025-07-01', validTo: '2025-09-30', status: 'Active', action: 'Edit' },
  { id: '22', title: 'Birthday Promo', type: 'Fixed', value: '$15', validFrom: '2025-01-01', validTo: '2025-12-31', status: 'Active', action: 'View' },
  { id: '23', title: 'Spring Sale', type: 'Percentage', value: '15%', validFrom: '2025-03-15', validTo: '2025-05-31', status: 'Expired', action: 'Edit' },
  { id: '24', title: 'Exclusive Offer', type: 'Fixed', value: '$60', validFrom: '2025-11-01', validTo: '2025-12-15', status: 'Pending', action: 'View' },
  { id: '25', title: 'Annual Deal', type: 'Percentage', value: '10%', validFrom: '2025-01-01', validTo: '2025-12-31', status: 'Active', action: 'Edit' }
];

export const mockLeaves = [
  { id: '1', staff: 'John Doe', date: '2025-09-01', action: 'Edit' },
  { id: '2', staff: 'Jane Smith', date: '2025-09-02', action: 'Edit' },
  { id: '3', staff: 'Alice Brown', date: '2025-09-03', action: 'Edit' },
  { id: '4', staff: 'Bob Johnson', date: '2025-09-04', action: 'Edit' },
  { id: '5', staff: 'Emma Wilson', date: '2025-09-05', action: 'Edit' },
  { id: '6', staff: 'Liam Davis', date: '2025-09-06', action: 'Edit' },
  { id: '7', staff: 'Olivia Martinez', date: '2025-09-07', action: 'Edit' },
  { id: '8', staff: 'Noah Lee', date: '2025-09-08', action: 'Edit' },
  { id: '9', staff: 'Sophia Clark', date: '2025-09-09', action: 'Edit' },
  { id: '10', staff: 'James Taylor', date: '2025-09-10', action: 'Edit' },
  { id: '11', staff: 'Isabella Garcia', date: '2025-09-11', action: 'Edit' },
  { id: '12', staff: 'Alexander Walker', date: '2025-09-12', action: 'Edit' },
  { id: '13', staff: 'Mia Rodriguez', date: '2025-09-13', action: 'Edit' },
  { id: '14', staff: 'Ethan Allen', date: '2025-09-14', action: 'Edit' },
  { id: '15', staff: 'Charlotte Young', date: '2025-09-15', action: 'Edit' },
  { id: '16', staff: 'Henry King', date: '2025-09-16', action: 'Edit' },
  { id: '17', staff: 'Harper Wright', date: '2025-09-17', action: 'Edit' },
  { id: '18', staff: 'Lucas Scott', date: '2025-09-18', action: 'Edit' },
  { id: '19', staff: 'Evelyn Adams', date: '2025-09-19', action: 'Edit' },
  { id: '20', staff: 'Jack Baker', date: '2025-09-20', action: 'Edit' },
  { id: '21', staff: 'Aria Nelson', date: '2025-09-21', action: 'Edit' },
  { id: '22', staff: 'Mason Carter', date: '2025-09-22', action: 'Edit' },
  { id: '23', staff: 'Lily Mitchell', date: '2025-09-23', action: 'Edit' },
  { id: '24', staff: 'Logan Perez', date: '2025-09-24', action: 'Edit' },
  { id: '25', staff: 'Grace Roberts', date: '2025-09-25', action: 'Edit' },
];